---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Simple Spot Instance Request Creation
    amazon.aws.ec2_spot_instance:
      launch_specification:
        image_id: ami-0022f774911c1d690
        key_name: EC2-AWS-SA
        instance_type: t2.medium
